In [2]:
a=5
a

5

In [3]:
a=6
a

6

In [6]:
a=4
c=9
print(a)
print(g)

4


NameError: name 'g' is not defined

In [7]:
open router.ai

SyntaxError: invalid syntax (1099961084.py, line 1)

In [11]:
a=4
a=5
a=110.5
a=

SyntaxError: invalid syntax (4177085745.py, line 4)

In [12]:
a=4
a=5
a=110.5
a=

SyntaxError: invalid syntax (4177085745.py, line 4)

In [16]:
import sys
sys.version

'3.13.5 | packaged by Anaconda, Inc. | (main, Jun 12 2025, 16:37:03) [MSC v.1929 64 bit (AMD64)]'

In [18]:
sys.version_info

sys.version_info(major=3, minor=13, micro=5, releaselevel='final', serial=0)

In [20]:
var=0
VAR

NameError: name 'VAR' is not defined

In [21]:
1ses=4.5
1ses

SyntaxError: invalid decimal literal (3193776455.py, line 1)

In [23]:
ses1=4.9
ses1

4.9

In [27]:
import.keyword
print(keyword.kwlist)

SyntaxError: invalid syntax (1865783430.py, line 1)

In [29]:
import keyword
keyword.kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [30]:
pass=23
pass

SyntaxError: invalid syntax (2340372038.py, line 1)

In [31]:
saha=11
saha

11

# python variable = identifier = object
# syntax (variable=value)

In [32]:
with=58
with

SyntaxError: invalid syntax (2523185245.py, line 1)

In [ ]:
#Type casing
convert one data type to other data type
All other data types to integers


In [33]:
int(1.67)


1

In [44]:
int(True)
int(False)
int(False)
int('37')

1

In [45]:
int(19+23kl)

SyntaxError: invalid decimal literal (2345685002.py, line 1)

In [46]:
In Type casting we cannot convert complex values,String to int or cannot define two arguements at a time

SyntaxError: invalid syntax (2737082328.py, line 1)

In [1]:
All other data types to float
float(456)
float('Sravanthi')
float('345.6338567836587')
float(true)
float(False)
float(True,False)

SyntaxError: invalid syntax (4291087585.py, line 1)

In [47]:
float(456)

456.0

In [48]:
float('Sravanthi')

ValueError: could not convert string to float: 'Sravanthi'

In [49]:
float('Five')

ValueError: could not convert string to float: 'Five'

In [50]:
float('345.6338567836587')


345.6338567836587

In [51]:
float(true)


NameError: name 'true' is not defined

In [52]:
float(False)


0.0

In [53]:
float(True,False)

TypeError: float expected at most 1 argument, got 2

In [55]:
float(True)

1.0

In [ ]:
All datatypes to String

In [56]:
str(45)

'45'

In [57]:
str(435.0997877)

'435.0997877'

In [58]:
str('223242442')

'223242442'

In [59]:
str(True)

'True'

In [60]:
str(true)


NameError: name 'true' is not defined

In [61]:
str(animal)

NameError: name 'animal' is not defined

In [62]:
str('animal')

'animal'

In [ ]:
all data type to boolean

In [63]:
bool(-12)

True

In [64]:
bool('Saha')

True

In [65]:
bool(0)


False

In [67]:
bool(3+5h)

SyntaxError: invalid decimal literal (1529615546.py, line 1)

In [68]:
bool(1+2j)

True

In [69]:
bool(3+5h)

SyntaxError: invalid decimal literal (1529615546.py, line 1)

In [70]:
h = 2
result = 3 + 5 * h  # This would be valid

In [73]:
h = 2
result = 3 + 5 * h  # This would be valid

In [74]:
complex(10)


(10+0j)

In [75]:
complex(True)

(1+0j)

In [76]:
complex(False)

0j

In [77]:
complex(23+4rg)

SyntaxError: invalid decimal literal (4135367474.py, line 1)

In [78]:
complex('20')

(20+0j)

In [79]:
complex('Sravanthi')

ValueError: complex() arg is a malformed string

In [ ]:
Data Type- User can define only one value to variable
Datastructure-User can define multiple values to variable

In [84]:
f=e*0

NameError: name 'e' is not defined

In [85]:
F=1e**0

SyntaxError: invalid decimal literal (2458429570.py, line 1)

# Assistant
The error occurs because of an invalid syntax in the expression `1e**0`. In Python, scientific notation is written as `1e0` (meaning 1×10^0), not `1e**0`.

Would you like me to provide the corrected code?

In [88]:
f=1e0
f

1.0

In [89]:
f=2e5
f

200000.0

In [91]:
f=5e5
f

500000.0

In [93]:
h=3.897e7
h

38970000.0

In [95]:
id(h)

2681847821040

In [ ]:
Address of the memory location is id

In [99]:
p=30
g=45
y=45
id(g)

140715424135464

In [100]:
print(id(g))

140715424135464


In [101]:
print(id(y))

140715424135464


In [103]:
print(id(p))

140715424134984


In [107]:
g= 'Sravanthi'
g

'Sravanthi'

In [109]:
print(g[-2])
print(g[-5])
print(g[-5])
print(g[2])
print(g[6])

h
a
a
a
t


In [110]:
g[-6:-4]

'va'

In [111]:
g[1:6]

'ravan'

In [112]:
g[0:3:6]

'S'

In [113]:
g[0:8:2]

'Saat'

In [115]:
g[::1]

'Sravanthi'

In [116]:
g[::3]

'Svt'

In [4]:
x=input()
y=input()
z==x+y 
print (z)



 enter x -=2
 enter y=4


NameError: name 'z' is not defined

In [6]:
st = input('enter a string')[1]
print (st)

enter a string 1


IndexError: string index out of range

In [7]:
st = input('enter a string')[1]
print (st)

enter a string 23


3


In [ ]:
st = input('enter a string')[5:8]
print (st)

In [ ]:
a= "11"
b =int(a)
print b
print(type(b)

In [3]:
import numpy as np

ModuleNotFoundError: No module named 'NumPy'

In [4]:
import numpy as np

In [5]:
mylist=[1,2,3,4,5]
mylist

[1, 2, 3, 4, 5]

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(5.0)


array([0., 1., 2., 3., 4.])

In [9]:
np.arange(30,-20)

array([], dtype=int64)

In [10]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
np.arange(20,10)

array([], dtype=int64)

In [14]:
ar=np.arange(-20,-40)
ar

array([], dtype=int64)

In [15]:
ar=np.arange(-40,-20)
ar

array([-40, -39, -38, -37, -36, -35, -34, -33, -32, -31, -30, -29, -28,
       -27, -26, -25, -24, -23, -22, -21])

In [16]:
np.arange(30,20,-10)

array([30])

In [17]:
np.arange()

TypeError: arange() requires stop to be specified.

In [18]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [19]:
np.arange(0,10,3,5,6)

TypeError: arange() takes from 0 to 4 positional arguments but 5 were given

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [23]:
two=np.zeros([2,2])
two

array([[0., 0.],
       [0., 0.]])

In [24]:
multi=np.zeros([4,7])
multi

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [28]:
multi=np.zeros([4,7])
print 'multi'
print'####'
print(type(multi))

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (767424727.py, line 2)

# Assistant
This error occurs because you're using Python 2 style print statements in Python 3. In Python 3, `print` is a function that requires parentheses.

Would you like me to provide the corrected code?

# Assistant
This error occurs because you're using Python 2 style print statements in Python 3. In Python 3, `print` is a function that requires parentheses.

Would you like me to provide the corrected code?

# User
yes

In [29]:
# Assistant
multi=np.zeros([4,7])
print(multi)  # Added parentheses for Python 3 compatibility
print('####')
print(type(multi))

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
####
<class 'numpy.ndarray'>


In [31]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [32]:
np.ones([4,6],dtype=int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [33]:
rand(3,2)

NameError: name 'rand' is not defined

In [34]:
random.rand(3,2)

NameError: name 'random' is not defined

In [35]:
np.random.rand(3,2)

array([[0.44977916, 0.55211584],
       [0.59083459, 0.75116879],
       [0.11511704, 0.79647809]])

In [36]:
np.random.rand(2.20,3,2)

TypeError: 'float' object cannot be interpreted as an integer

In [37]:
np.random.rand(2.20,3,)

TypeError: 'float' object cannot be interpreted as an integer

In [39]:
np.random.rand(2,10,3)

array([[[8.27847341e-01, 3.79881737e-02, 2.17163354e-01],
        [8.20051367e-01, 6.29868149e-01, 8.79777520e-01],
        [2.56125235e-01, 5.93310326e-02, 4.34786399e-01],
        [7.76238449e-01, 6.88615674e-01, 9.04963404e-01],
        [1.92720517e-01, 7.96683097e-01, 6.10956271e-01],
        [5.42999844e-01, 8.12589691e-01, 4.89087839e-01],
        [8.21259579e-01, 5.21491512e-01, 1.74581307e-01],
        [6.37486062e-01, 4.50187358e-01, 4.78161743e-01],
        [6.63108611e-01, 2.46131626e-01, 5.18645068e-01],
        [3.62999697e-01, 9.18138242e-01, 3.44998376e-01]],

       [[3.44929805e-01, 2.89976517e-02, 9.71251335e-01],
        [9.17435621e-01, 6.67992764e-04, 6.13308909e-01],
        [2.00554344e-02, 7.71486728e-01, 9.50974081e-01],
        [7.58657331e-02, 8.23873632e-03, 8.65361724e-01],
        [1.69865238e-02, 7.31543587e-01, 4.86197105e-01],
        [4.10276986e-01, 2.09091862e-01, 9.50734558e-01],
        [3.81311332e-01, 9.93389686e-01, 9.58566956e-01],
        [8.3

In [49]:
np.random.randint(2,20,9)

array([15, 14,  3,  5, 19,  2, 12, 19, 18], dtype=int32)

In [47]:
np.random.randint(9,18)

11

In [52]:
np.random.randint(-30,20,10)

array([-29, -23,  10,   2, -19, -23, -23, -22, -23,  -7], dtype=int32)

In [53]:
np.random.randint(20,30,10,5)

TypeError: Cannot interpret '5' as a data type

In [56]:
np.random.randint(10,40,(10,10))

array([[29, 11, 17, 18, 15, 17, 28, 30, 12, 18],
       [23, 23, 17, 21, 15, 39, 32, 34, 21, 15],
       [29, 11, 21, 38, 16, 23, 19, 27, 27, 22],
       [38, 30, 31, 20, 19, 12, 27, 17, 22, 35],
       [37, 23, 33, 32, 17, 35, 33, 36, 10, 22],
       [25, 34, 23, 28, 22, 14, 20, 15, 21, 35],
       [35, 29, 11, 14, 13, 29, 33, 22, 30, 37],
       [17, 36, 38, 20, 12, 12, 14, 37, 36, 14],
       [36, 16, 10, 10, 39, 38, 22, 33, 24, 39],
       [32, 17, 26, 12, 22, 14, 21, 38, 15, 38]], dtype=int32)

In [57]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [58]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [61]:
np.arange(1,35).reshape(5,7)

ValueError: cannot reshape array of size 34 into shape (5,7)

In [64]:
np.arange(0,35)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34])

In [65]:
np.arange(0,35).reshape(5,7)

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [ ]:
#slicing in matrix

In [66]:
p=np.random.randint(10,20,(5,4))
p

array([[18, 15, 13, 13],
       [14, 16, 16, 14],
       [19, 15, 16, 18],
       [18, 12, 19, 15],
       [16, 10, 10, 16]], dtype=int32)

In [67]:
type(p)

numpy.ndarray

In [68]:
p[:]

array([[18, 15, 13, 13],
       [14, 16, 16, 14],
       [19, 15, 16, 18],
       [18, 12, 19, 15],
       [16, 10, 10, 16]], dtype=int32)

In [69]:
p[1:3]

array([[14, 16, 16, 14],
       [19, 15, 16, 18]], dtype=int32)

In [1]:
p[1,2]


NameError: name 'p' is not defined

In [2]:
p=np.random.randint(10,20,(5,4))
p


NameError: name 'np' is not defined

In [4]:
import numpy as np

In [5]:
p=np.random.randint(10,20,(5,4))
p

array([[19, 10, 11, 16],
       [10, 10, 14, 15],
       [14, 16, 14, 18],
       [17, 19, 10, 14],
       [13, 16, 16, 12]], dtype=int32)

In [6]:
p[0:-2]

array([[19, 10, 11, 16],
       [10, 10, 14, 15],
       [14, 16, 14, 18]], dtype=int32)

In [7]:
p[-5,-3]

np.int32(10)

In [8]:
p[::-2]

array([[13, 16, 16, 12],
       [14, 16, 14, 18],
       [19, 10, 11, 16]], dtype=int32)

In [9]:
p[:-3]

array([[19, 10, 11, 16],
       [10, 10, 14, 15]], dtype=int32)

In [12]:
arr2=[10,40,60]
arr2

[10, 40, 60]

# Assistant
The error occurs because you're trying to use a variable `arr` that hasn't been defined yet. Additionally, there's a syntax error in how you're trying to create the array.

Would you like me to provide the corrected code?

In [19]:
mat=np.random.randint(10,200,10)
mat

array([ 18, 196, 159,  44,  71,  67,  25, 169, 185, 162], dtype=int32)

In [21]:
a=np.array([11,2,3])
a

array([11,  2,  3])

In [28]:
b=np.array(20,10,1)
b

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

# Assistant
The error occurs because of two issues in your code:

1. There's a typo in the function name: you used `arrange` instead of the correct NumPy function `arange` (without the second 'r').

2. You're using square brackets `[]` instead of parentheses `()` when calling the function.

Would you like me to provide the corrected code?

In [30]:
f=np.eye(4)
print(f)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [34]:
np.array([1,2,3])

array([1, 2, 3])

In [37]:
a1=np.array([1,2,3])
reshapes=np.reshape(a1,(3,1))
reshapes

array([[1],
       [2],
       [3]])

In [39]:
f1=np.array([[1,2],[3,4]])
flatters=np.ravel(f1)
flatters

array([1, 2, 3, 4])

In [41]:
e1=np.array([[1,2],[3,4]])
trans=np.transpose(e1)
trans

array([[1, 3],
       [2, 4]])